# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fcc785ebcec20baa674f61d9ef2fdbf4f7e376f91eef8d7f9574962d4cbe32399a09fb92fc21abf06d30e80bc7a7e6691711c5fc0994ef0a8951b5275a44f6d4

test:
  secret_key_base: e9bf317b08087dfbd0f31a037313adf43663748d53a25ddf3760dcd6ebfa81c475dbe5ef510e65fa341b55818243da38a4786925dd1c3af8d0d15651b05c5d88

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
